[package]
name = "counter"
version = "1.0.0"
authors = []

[addresses]
counter_app = "e4b58bcc62759559c7a9f4c63a5fa91711b3ff3381db404ca82ea9feb974df06"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
